from __future__ import annotations

from enum import Enum
from pathlib import Path
from typing import Any, Callable, ClassVar

class SurpModelError(Exception): ...
class SurpModelDefinitionError(SurpModelError): ...
class SurpFieldError(SurpModelError):
    field_path: str
    expected: str
    got: str
    message: str
class SurpValidationError(SurpModelError):
    errors: list[SurpFieldError]
class SurpEncodeModelError(SurpModelError): ...
class SurpDecodeModelError(SurpModelError): ...
class SurpQueryError(SurpModelError): ...

class FieldInfo:
    name: str
    rfc_type: Any
    required: bool
    default: Any
    default_factory: Callable[[], Any] | None
    doc: str | None
    binding: str | None

class Field:
    def __new__(
        cls,
        *,
        required: bool = True,
        default: Any = ...,
        default_factory: Callable[[], Any] | None = None,
        doc: str | None = None,
        binding: str | None = None,
    ) -> Any: ...
    def __init__(
        self,
        *,
        required: bool = True,
        default: Any = ...,
        default_factory: Callable[[], Any] | None = None,
        doc: str | None = None,
        binding: str | None = None,
    ) -> None: ...

class SurpVariant:
    variant: str
    payload: dict[str, Any] | Any | None
    def __init__(self, variant: str, payload: dict[str, Any] | Any | None = None) -> None: ...

class SurpStream:
    annotations: dict[str, Any]
    def __init__(self, annotations: dict[str, Any] | None = None) -> None: ...

class SurpModel:
    __rfc_type__: ClassVar[str]
    __strict__: ClassVar[bool]
    __surp_fields__: ClassVar[dict[str, FieldInfo]]
    def __init__(self, **kwargs: Any) -> None: ...
    def validate(self) -> None: ...
    def collect_errors(self) -> list[SurpFieldError]: ...
    def to_ctn(self, indent: int = 2) -> str: ...
    def to_cbf(self, *, alignment: int = 4, with_symtab: bool = True) -> bytes: ...
    def to_surp(self, *, dedup: bool = True, sort_keys: bool = True) -> bytes: ...
    @classmethod
    def from_ctn(cls, text: str, *, validate: bool = True) -> Any: ...
    @classmethod
    def from_cbf(cls, data: bytes, *, validate: bool = True) -> Any: ...
    @classmethod
    def from_rfc_value(cls, value: Any, *, validate: bool = True) -> Any: ...
    @classmethod
    def from_surp(cls, data: bytes, *, validate: bool = True) -> Any: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any], *, validate: bool = True) -> Any: ...
    def query(self, expr: str) -> list[Any]: ...
    def query_one(self, expr: str) -> Any: ...
    @classmethod
    def schema_ctn(cls) -> str: ...
    @classmethod
    def schema_json(cls) -> dict[str, Any]: ...
    def to_dict(self) -> dict[str, Any]: ...

class SurpDocument(SurpModel): ...
class SurpSymbolEnum(Enum): ...  # type: ignore[misc]
SurpEnum = SurpSymbolEnum

def annotation(name: str, value: Any | None = None) -> Any: ...
def generate_model_stubs(*classes: type) -> str: ...
def write_model_stubs(path: str | Path, *classes: type) -> None: ...

class _RegistryModule:
    def register(self, cls: type) -> type: ...
    def get(self, name: str) -> type | None: ...
    def register_module(self, module: str | Any) -> None: ...
    def all_models(self) -> dict[str, type]: ...

registry: _RegistryModule
