/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSpecRouteImport } from './routes/docs.spec'
import { Route as DocsRustApiRouteImport } from './routes/docs.rust-api'
import { Route as DocsRfc001RouteImport } from './routes/docs.rfc001'
import { Route as DocsPythonApiRouteImport } from './routes/docs.python-api'
import { Route as DocsMcpRouteImport } from './routes/docs.mcp'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSpecRoute = DocsSpecRouteImport.update({
  id: '/docs/spec',
  path: '/docs/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRustApiRoute = DocsRustApiRouteImport.update({
  id: '/docs/rust-api',
  path: '/docs/rust-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRfc001Route = DocsRfc001RouteImport.update({
  id: '/docs/rfc001',
  path: '/docs/rfc001',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPythonApiRoute = DocsPythonApiRouteImport.update({
  id: '/docs/python-api',
  path: '/docs/python-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/docs/mcp',
  path: '/docs/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/examples': typeof ExamplesRoute
  '/getting-started': typeof GettingStartedRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/python-api': typeof DocsPythonApiRoute
  '/docs/rfc001': typeof DocsRfc001Route
  '/docs/rust-api': typeof DocsRustApiRoute
  '/docs/spec': typeof DocsSpecRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/examples': typeof ExamplesRoute
  '/getting-started': typeof GettingStartedRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/python-api': typeof DocsPythonApiRoute
  '/docs/rfc001': typeof DocsRfc001Route
  '/docs/rust-api': typeof DocsRustApiRoute
  '/docs/spec': typeof DocsSpecRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/cookies': typeof CookiesRoute
  '/examples': typeof ExamplesRoute
  '/getting-started': typeof GettingStartedRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/python-api': typeof DocsPythonApiRoute
  '/docs/rfc001': typeof DocsRfc001Route
  '/docs/rust-api': typeof DocsRustApiRoute
  '/docs/spec': typeof DocsSpecRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/changelog'
    | '/community'
    | '/cookies'
    | '/examples'
    | '/getting-started'
    | '/help'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/cli'
    | '/docs/mcp'
    | '/docs/python-api'
    | '/docs/rfc001'
    | '/docs/rust-api'
    | '/docs/spec'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/changelog'
    | '/community'
    | '/cookies'
    | '/examples'
    | '/getting-started'
    | '/help'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/cli'
    | '/docs/mcp'
    | '/docs/python-api'
    | '/docs/rfc001'
    | '/docs/rust-api'
    | '/docs/spec'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/benchmarks'
    | '/changelog'
    | '/community'
    | '/cookies'
    | '/examples'
    | '/getting-started'
    | '/help'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/cli'
    | '/docs/mcp'
    | '/docs/python-api'
    | '/docs/rfc001'
    | '/docs/rust-api'
    | '/docs/spec'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BenchmarksRoute: typeof BenchmarksRoute
  ChangelogRoute: typeof ChangelogRoute
  CommunityRoute: typeof CommunityRoute
  CookiesRoute: typeof CookiesRoute
  ExamplesRoute: typeof ExamplesRoute
  GettingStartedRoute: typeof GettingStartedRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsPythonApiRoute: typeof DocsPythonApiRoute
  DocsRfc001Route: typeof DocsRfc001Route
  DocsRustApiRoute: typeof DocsRustApiRoute
  DocsSpecRoute: typeof DocsSpecRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/spec': {
      id: '/docs/spec'
      path: '/docs/spec'
      fullPath: '/docs/spec'
      preLoaderRoute: typeof DocsSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/rust-api': {
      id: '/docs/rust-api'
      path: '/docs/rust-api'
      fullPath: '/docs/rust-api'
      preLoaderRoute: typeof DocsRustApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/rfc001': {
      id: '/docs/rfc001'
      path: '/docs/rfc001'
      fullPath: '/docs/rfc001'
      preLoaderRoute: typeof DocsRfc001RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/python-api': {
      id: '/docs/python-api'
      path: '/docs/python-api'
      fullPath: '/docs/python-api'
      preLoaderRoute: typeof DocsPythonApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/docs/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BenchmarksRoute: BenchmarksRoute,
  ChangelogRoute: ChangelogRoute,
  CommunityRoute: CommunityRoute,
  CookiesRoute: CookiesRoute,
  ExamplesRoute: ExamplesRoute,
  GettingStartedRoute: GettingStartedRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  DocsCliRoute: DocsCliRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsPythonApiRoute: DocsPythonApiRoute,
  DocsRfc001Route: DocsRfc001Route,
  DocsRustApiRoute: DocsRustApiRoute,
  DocsSpecRoute: DocsSpecRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
