from __future__ import annotations

from os import PathLike
from typing import Any, BinaryIO, Union, overload

from . import rfc001 as rfc001
from ._types import Compression
from .exceptions import (
    SurpChecksumError,
    SurpDecodeError,
    SurpEncodeError,
    SurpError,
    SurpRfcError,
    SurpTypeError,
)

__version__: str

def dumps(
    obj: Any,
    *,
    compression: Compression | None = None,
    dedup: bool = False,
    sort_keys: bool = False,
) -> bytes: ...

def loads(data: bytes, *, strict: bool = True, max_depth: int = 128) -> Any: ...

def dump(
    obj: Any,
    fp: BinaryIO,
    *,
    compression: Compression | None = None,
    dedup: bool = False,
    sort_keys: bool = False,
) -> None: ...

def load(fp: BinaryIO, *, strict: bool = True, max_depth: int = 128) -> Any: ...
def encode(obj: Any) -> bytes: ...
def decode(data: bytes) -> Any: ...
def encode_to_file(obj: Any, path: Union[str, PathLike[str]]) -> None: ...
def decode_from_file(path: Union[str, PathLike[str]]) -> Any: ...
def parse_text(text: str) -> Any: ...
def pretty_print(obj: Any, indent: int = 2) -> str: ...
def to_value(obj: Any, *, sort_keys: bool = False) -> SurpValue: ...
def loads_value(
    data: bytes, *, strict: bool = True, max_depth: int = 128
) -> SurpValue | list[SurpValue]: ...
def parse_text_value(text: str) -> SurpValue: ...

class SurpValue:
    kind: str
    is_null: bool
    is_scalar: bool
    is_array: bool
    is_object: bool
    value: Any | None
    def as_python(self) -> Any: ...
    @overload
    def __getitem__(self, key: str) -> SurpValue: ...
    @overload
    def __getitem__(self, key: int) -> SurpValue: ...
    @overload
    def get(self, key: str) -> SurpValue | None: ...
    @overload
    def get(self, key: int) -> SurpValue | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[SurpValue]: ...
    def items(self) -> list[tuple[str, SurpValue]]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...

class Encoder:
    def __init__(self, *, sort_keys: bool = False) -> None: ...
    def enable_dedup(self) -> None: ...
    def set_compression(self, comp: Compression) -> None: ...
    def encode(self, obj: Any) -> None: ...
    def finish(self) -> bytes: ...
    def finish_to_file(self, path: Union[str, PathLike[str]]) -> None: ...

class SurpDecoder:
    def __init__(self, data: bytes, *, max_depth: int = 128) -> None: ...
    def decode_all(self) -> list[Any]: ...
