from __future__ import annotations

from os import PathLike
from typing import Any, BinaryIO, Literal, overload

__version__: str

class SurpError(Exception): ...
class SurpEncodeError(SurpError): ...
class SurpDecodeError(SurpError): ...
class SurpChecksumError(SurpDecodeError): ...
class SurpTypeError(SurpEncodeError): ...
class SurpRfcError(SurpError): ...

Compression = Literal["lz4", "zstd", "snappy", "none"]

def dumps(
    obj: Any,
    *,
    compression: Compression | None = None,
    dedup: bool = False,
    sort_keys: bool = False,
) -> bytes: ...
def loads(data: bytes, *, strict: bool = True, max_depth: int = 128) -> Any: ...
def dump(
    obj: Any,
    fp: BinaryIO,
    *,
    compression: Compression | None = None,
    dedup: bool = False,
    sort_keys: bool = False,
) -> None: ...
def load(fp: BinaryIO, *, strict: bool = True, max_depth: int = 128) -> Any: ...
def encode(obj: Any) -> bytes: ...
def decode(data: bytes) -> Any: ...
def encode_to_file(obj: Any, path: str | PathLike[str]) -> None: ...
def decode_from_file(path: str | PathLike[str]) -> Any: ...
def parse_text(text: str) -> Any: ...
def pretty_print(obj: Any, indent: int = 2) -> str: ...
def to_value(obj: Any, *, sort_keys: bool = False) -> SurpValue: ...
def loads_value(
    data: bytes, *, strict: bool = True, max_depth: int = 128
) -> SurpValue | list[SurpValue]: ...
def parse_text_value(text: str) -> SurpValue: ...

class SurpValue:
    kind: str
    is_null: bool
    is_scalar: bool
    is_array: bool
    is_object: bool
    value: Any | None
    def as_python(self) -> Any: ...
    @overload
    def __getitem__(self, key: str) -> SurpValue: ...
    @overload
    def __getitem__(self, key: int) -> SurpValue: ...
    @overload
    def get(self, key: str) -> SurpValue | None: ...
    @overload
    def get(self, key: int) -> SurpValue | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[SurpValue]: ...
    def items(self) -> list[tuple[str, SurpValue]]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...

class Encoder:
    def __init__(self, *, sort_keys: bool = False) -> None: ...
    def enable_dedup(self) -> None: ...
    def set_compression(self, comp: Compression) -> None: ...
    def encode(self, obj: Any) -> None: ...
    def finish(self) -> bytes: ...
    def finish_to_file(self, path: str | PathLike[str]) -> None: ...

class SurpDecoder:
    def __init__(self, data: bytes, *, max_depth: int = 128) -> None: ...
    def decode_all(self) -> list[Any]: ...

RFC001_CBF_MAGIC: bytes
RFC001_CBF_HEADER_SIZE: int

def rfc_parse_ctn(text: str) -> dict[str, Any]: ...
def rfc_format_ctn(text: str) -> str: ...
def rfc_compile_ctn(text: str, *, with_symtab: bool = True, alignment: int = 0) -> bytes: ...
def rfc_decode_cbf(data: bytes) -> dict[str, Any]: ...
def rfc_cbf_to_ctn(data: bytes) -> str: ...
def rfc_query_cbf(data: bytes, query: str, *, as_ctn: bool = False) -> list[Any]: ...
def rfc_query_ctn(text: str, query: str, *, as_ctn: bool = False) -> list[Any]: ...
def rfc_parse_ctn_model(text: str) -> RfcDocument: ...
def rfc_decode_cbf_model(data: bytes) -> RfcDecodedCbf: ...
def rfc_query_cbf_model(data: bytes, query: str) -> list[RfcValue]: ...
def rfc_query_ctn_model(text: str, query: str) -> list[RfcValue]: ...

class RfcAnnotation:
    name: str
    value: dict[str, Any] | None
    def to_dict(self) -> dict[str, Any]: ...

class RfcField:
    name: str
    value: RfcValue
    def to_dict(self) -> dict[str, Any]: ...

class RfcBinding:
    name: str
    value: RfcValue
    def to_dict(self) -> dict[str, Any]: ...

class RfcHeader:
    magic: str
    cbf_version: int
    ctn_version: int
    flags: int
    alignment: int
    schema_hash_prefix: bytes
    root_offset: int
    symtab_offset: int
    index_offset: int
    self_describing: bool
    has_symtab: bool
    has_index: bool
    def to_dict(self) -> dict[str, Any]: ...

class RfcDocument:
    annotations: list[RfcAnnotation]
    uses: list[str]
    bindings: list[RfcBinding]
    root: RfcValue | None
    def effective_root(self) -> RfcValue: ...
    def binding_names(self) -> list[str]: ...
    def annotation_names(self) -> list[str]: ...
    def binding(self, name: str) -> RfcBinding | None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_ctn(self) -> str: ...

class RfcDecodedCbf:
    header: RfcHeader
    symbols: list[str]
    document: RfcDocument
    ctn: str
    def to_dict(self) -> dict[str, Any]: ...

class RfcValue:
    kind: str
    is_scalar: bool
    is_empty: bool
    type_name: str | None
    scalar_type: str | None
    scalar_value: Any | None
    variant: str | None
    payload_kind: str | None
    elem_type: str | None
    element_type: str | None
    shape: list[int | None]
    data_kind: str | None
    @overload
    def __getitem__(self, key: str) -> RfcValue: ...
    @overload
    def __getitem__(self, key: int) -> RfcValue: ...
    @overload
    def get(self, key: str) -> RfcValue | None: ...
    @overload
    def get(self, key: int) -> RfcValue | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[RfcValue]: ...
    def fields(self) -> list[RfcField]: ...
    def annotations(self) -> list[RfcAnnotation]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_ctn(self) -> str: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
