from __future__ import annotations

class SurpError(Exception): ...
class SurpEncodeError(SurpError): ...
class SurpDecodeError(SurpError): ...
class SurpChecksumError(SurpDecodeError): ...
class SurpTypeError(SurpEncodeError): ...
class SurpRfcError(SurpError): ...
