from __future__ import annotations

from typing import Any, overload

from ._types import RfcDecodedCbf, RfcDocument

CBF_MAGIC: bytes
CBF_HEADER_SIZE: int

def parse_ctn(text: str) -> RfcDocument: ...
def normalize_ctn(text: str) -> str: ...
def compile_ctn(text: str, *, with_symtab: bool = True, alignment: int = 0) -> bytes: ...
def decode_cbf(data: bytes) -> RfcDecodedCbf: ...
def cbf_to_ctn(data: bytes) -> str: ...

@overload
def query_cbf(data: bytes, query: str, *, as_ctn: bool = False) -> list[dict[str, Any]]: ...
@overload
def query_cbf(data: bytes, query: str, *, as_ctn: bool) -> list[Any]: ...

@overload
def query_ctn(text: str, query: str, *, as_ctn: bool = False) -> list[dict[str, Any]]: ...
@overload
def query_ctn(text: str, query: str, *, as_ctn: bool) -> list[Any]: ...
