from __future__ import annotations

from typing import Any, Literal, overload

from ._types import RfcDecodedCbf as RfcDecodedCbfDict, RfcDocument as RfcDocumentDict

CBF_MAGIC: bytes
CBF_HEADER_SIZE: int

def parse_ctn(text: str) -> RfcDocumentDict: ...
def normalize_ctn(text: str) -> str: ...
def compile_ctn(text: str, *, with_symtab: bool = True, alignment: int = 0) -> bytes: ...
def decode_cbf(data: bytes) -> RfcDecodedCbfDict: ...
def cbf_to_ctn(data: bytes) -> str: ...
def parse_ctn_model(text: str) -> RfcDocumentModel: ...
def decode_cbf_model(data: bytes) -> RfcDecodedCbfModel: ...
def query_cbf_model(data: bytes, query: str) -> list[RfcValue]: ...
def query_ctn_model(text: str, query: str) -> list[RfcValue]: ...

@overload
def query_cbf(
    data: bytes, query: str, *, as_ctn: Literal[False] = False
) -> list[dict[str, Any]]: ...
@overload
def query_cbf(data: bytes, query: str, *, as_ctn: Literal[True]) -> list[str]: ...

@overload
def query_ctn(
    text: str, query: str, *, as_ctn: Literal[False] = False
) -> list[dict[str, Any]]: ...
@overload
def query_ctn(text: str, query: str, *, as_ctn: Literal[True]) -> list[str]: ...

class RfcAnnotation:
    name: str
    value: dict[str, Any] | None
    def to_dict(self) -> dict[str, Any]: ...

class RfcField:
    name: str
    value: RfcValue
    def to_dict(self) -> dict[str, Any]: ...

class RfcBinding:
    name: str
    value: RfcValue
    def to_dict(self) -> dict[str, Any]: ...

class RfcHeader:
    magic: str
    cbf_version: int
    ctn_version: int
    flags: int
    alignment: int
    schema_hash_prefix: bytes
    root_offset: int
    symtab_offset: int
    index_offset: int
    self_describing: bool
    has_symtab: bool
    has_index: bool
    def to_dict(self) -> dict[str, Any]: ...

class RfcDocumentModel:
    annotations: list[RfcAnnotation]
    uses: list[str]
    bindings: list[RfcBinding]
    root: RfcValue | None
    def effective_root(self) -> RfcValue: ...
    def binding_names(self) -> list[str]: ...
    def annotation_names(self) -> list[str]: ...
    def binding(self, name: str) -> RfcBinding | None: ...
    def to_dict(self) -> RfcDocumentDict: ...
    def to_ctn(self) -> str: ...

class RfcDecodedCbfModel:
    header: RfcHeader
    symbols: list[str]
    document: RfcDocumentModel
    ctn: str
    def to_dict(self) -> RfcDecodedCbfDict: ...

class RfcValue:
    kind: str
    is_scalar: bool
    is_empty: bool
    type_name: str | None
    scalar_type: str | None
    scalar_value: Any | None
    variant: str | None
    payload_kind: str | None
    elem_type: str | None
    element_type: str | None
    shape: list[int | None]
    data_kind: str | None
    @overload
    def __getitem__(self, key: str) -> RfcValue: ...
    @overload
    def __getitem__(self, key: int) -> RfcValue: ...
    @overload
    def get(self, key: str) -> RfcValue | None: ...
    @overload
    def get(self, key: int) -> RfcValue | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[RfcValue]: ...
    def fields(self) -> list[RfcField]: ...
    def annotations(self) -> list[RfcAnnotation]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_ctn(self) -> str: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...

RfcDocument = RfcDocumentModel
RfcDecodedCbf = RfcDecodedCbfModel
